# Numpy

In [1]:
import pandas as pd
baseball = pd.read_csv('baseball.csv')

In [2]:
import numpy as np

height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.8, 88.4, 68.7]

np_height = np.array(height)
np_weight = np.array(weight)

bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.81867925, 24.7473475 , 21.44127836])

In [3]:
# otra forma de slicing en array
bmi[bmi > 23]

array([24.7473475])

In [4]:
height_in = baseball['Height']
weight_lb = baseball['Weight']

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


In [5]:
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

200
[73 74 72 73 69 72 73 75 75 73 72]


In [6]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.8, 88.4, 68.7]])

print(np_2d)
print(np_2d.shape)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.8  88.4  68.7 ]]
(2, 5)


In [7]:
print(np_2d[0][2])
print(np_2d[0,2])

1.71
1.71


In [8]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.8 ]])

In [9]:
# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(1015, 7)


In [10]:
np_baseball = np.array(baseball[['Height','Weight']])

# Print out the 50th row of np_baseball
print(np_baseball[49])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]
print(np_weight_lb)

# Print out height of 124th player
print(np_baseball[123,0]) 


[ 70 195]
[180 215 210 ... 205 190 195]
75


In [11]:
np_baseball = np.array(baseball[['Height','Weight','Age']])

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]


In [12]:
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 73.6896551724138
Median: 74.0
Standard Deviation: 2.312791881046546
Correlation: [[1.         0.53153932]
 [0.53153932 1.        ]]


In [14]:
### EXTRA CANDY

# Simulación de info

height = np.round(np.random.normal(1.75, 0.20, 5000),2)
weight = np.round(np.random.normal(60.32, 15, 5000),2)

np_city = np.column_stack((height,weight))